modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/novumscientiateam/Modular-Toolkit"
[[mods]]
modId="modulartoolkit"
version="${file.jarVersion}"
displayName="Modular Toolkit"
authors="TheEmosewaPixel, Nartz24, RonM"
description="A mod adding customizable tools based on Pixel Lib materials."
[[dependencies.modulartoolkit]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modulartoolkit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.modulartoolkit]]
     modId="pixellib"
     mandatory=true
     versionRange="[1.0.5,]"
     ordering="AFTER"
     side="BOTH"